[template]

[placeholders.identifier]
prompt = "Application identifier (e.g., com.example.app)"
type = "string"
default = "com.example.{{ project-name | kebab_case }}"
regex = "^[a-zA-Z][a-zA-Z0-9.-]*$"