[package]
name = "mobile"
version = "0.1.0"
edition = "2024"
authors = ["{{author}}"]
description = "{{description}} - Mobile App"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }

[features]
default = []
ios = []
android = []