[package]
name = "ui"
version = "0.1.0"
edition = "2024"
authors = ["{{authors}}"]
description = "{{description}} - Shared UI Components"

[dependencies]
dioxus = { workspace = true }
api = { workspace = true }