[package]
name = "ui"
version = "0.1.0"
edition = "2024"
authors = ["{{authors | default: 'Your Name <your.email@example.com>'}}"]
description = "A fullstack Dioxus app with Tauri - Shared UI Components"

[dependencies]
dioxus = { workspace = true }
api = { workspace = true }