[application]
name = "{{ project-name | snake_case }}-desktop"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "{{ project-name | title_case}}"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.devserver]
port = 1420